services:
  app:
    build: .
    container_name: simulation-controller
    ports:
      - "3000:3000"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 2s
      timeout: 1s
      retries: 3
