[[drone]]
id = 1
connected_node_ids = [10, 20]
pdr = 0.0

[[server]]
id = 10
connected_drone_ids = [1]
server_type = "Content"
base_path = "/tmp/rust"

[[server]]
id = 20
connected_drone_ids = [1]
server_type = "Communication"
base_path = "/tmp/rust"

[[client]]
id = 200
connected_drone_ids = [1]
